# Site settings
# in the templates available like {{ site.myvariable }}.
title: Homepage for Nirajan Rajkarnikar
email: nrajkarn@alumni.cmu.edu
brand: Nirajan Rajkarnikar
headline: Software Developer, Engineer and Analyst
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
copyright: 2016 Nirajan Rajkarnikar. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: nrajkarn@alumni.cmu.edu
phone: 

# Tracking
googleAnalitycsID: UA-85434136-1

